Question 1

a)

In [2]:
import numpy as np
from scipy.signal import convolve2d

# Convolve the 2D image I with the 2D kernel G
# I: 2D image
I = np.array([[5, 4, 0, 3],
              [6, 2, 1, 8],
              [7, 9, 4, 2],
              [8, 3, 6, 1]])
# G: 2D kernel
G = (1.0 / 16) * np.array([[1, 2, 1],
                           [2, 4, 2],
                           [1, 2, 1]])

# Replicate-padding the input image
padded_I = np.pad(I, pad_width=1, mode='edge')

# Convolve the image with the kernel
convolved_I = convolve2d(padded_I, G, mode='valid')

# Print the result
print("\nConvolved image:\n")
print(convolved_I)

# And if we want to convert the result to integers:
output = convolved_I.astype(int)
print("\n\nConvolved image (as integers):\n")
print(output)


Convolved image:

[[4.8125 3.125  2.0625 3.25  ]
 [5.5625 4.     3.125  4.3125]
 [6.6875 5.5625 4.125  3.375 ]
 [6.9375 5.5625 4.1875 2.3125]]


Convolved image (as integers):

[[4 3 2 3]
 [5 4 3 4]
 [6 5 4 3]
 [6 5 4 2]]


b)

In [3]:
import numpy as np
from scipy.signal import convolve2d

# Convolve the 2D image I with a horizontal and a vertical 1D kernel
# I: 2D image
I = np.array([[5, 4, 0, 3],
              [6, 2, 1, 8],
              [7, 9, 4, 2],
              [8, 3, 6, 1]])
# G: 2 kernels
G1 = (1.0 / 4) * np.array([1, 2, 1])
G2 = (1.0 / 4) * np.array([[1],
                           [2],
                           [1]])
# Replicate-padding the input image
padded_I = np.pad(I, ((1, 1), (1, 1)), mode='edge')

# Convolve the image with the horizontal kernel
convolved_I_horizontal = convolve2d(padded_I, G1[np.newaxis, :], mode='valid')
# Convolve the convolved_I_horizontal with the vertical kernel
convolved_I_vertical = convolve2d(convolved_I_horizontal, G2, mode='valid')

# Print the result
print("\nConvolved image (Horizontal-First)::\n")
print(convolved_I_vertical)

# And if we want to convert the result to integers:
output = convolved_I_vertical.astype(int)
print("\n\nConvolved image (Horizontal-First) (as integers):\n")
print(output)

# Convolve the image with the horizontal kernel
convolved_I_vertical2 = convolve2d(padded_I, G2, mode='valid')
# Convolve the convolved_I_horizontal with the vertical kernel
convolved_I_horizontal2 = convolve2d(convolved_I_vertical2, G1[np.newaxis, :], mode='valid')

# Print the result
print("\nConvolved image (Vertical-First)::\n")
print(convolved_I_horizontal2)

# And if we want to convert the result to integers:
output2 = convolved_I_horizontal2.astype(int)
print("\n\nConvolved image (Vertical-First) (as integers):\n")
print(output2)



Convolved image (Horizontal-First)::

[[4.8125 3.125  2.0625 3.25  ]
 [5.5625 4.     3.125  4.3125]
 [6.6875 5.5625 4.125  3.375 ]
 [6.9375 5.5625 4.1875 2.3125]]


Convolved image (Horizontal-First) (as integers):

[[4 3 2 3]
 [5 4 3 4]
 [6 5 4 3]
 [6 5 4 2]]

Convolved image (Vertical-First)::

[[4.8125 3.125  2.0625 3.25  ]
 [5.5625 4.     3.125  4.3125]
 [6.6875 5.5625 4.125  3.375 ]
 [6.9375 5.5625 4.1875 2.3125]]


Convolved image (Vertical-First) (as integers):

[[4 3 2 3]
 [5 4 3 4]
 [6 5 4 3]
 [6 5 4 2]]


The results are the same because Convolution is associative and the order does not matter.

c)

Because the kernel used in part b is the seperable kernel of part a, they lead to the same results.